// components/commands.js

const commands = [
  "pwd",
  "ss",
  "netstat",
  "ip addr",
  "ifconfig",
  "vim file.txt",
  "ls",
  "cd /home",
  "mkdir testDir",
  "touch newfile.txt",
  "rm newfile.txt",
  "mv oldfile.txt newfile.txt",
  "cat newfile.txt",
  "echo 'Hello World' > file.txt",
  "cp file.txt copy.txt",
  "ps",
  "kill 1234",
  "top",
  "htop",
  "date",
  "whoami",
  "hostname",
  "uname -a",
  "uptime",
  "cal",
  "bc",
  "df -h",
  "du -sh *",
  "free -m",
  "id",
  "who",
  "w",
  "last",
  "grep 'search term' file.txt",
  "which ls",
  "locate file.txt",
  "diff file1.txt file2.txt",
  "sort file.txt",
  "uniq file.txt",
  "head file.txt",
  "tail file.txt",
  "wc file.txt",
  "tee file.txt",
  "awk '{print $1}' file.txt",
  "sed 's/old/new/g' file.txt",
  "cut -d':' -f1 /etc/passwd",
  "tr 'a-z' 'A-Z'",
  "stat file.txt",
  "file file.txt",
  "lsblk",
  "parted /dev/sda print",
  "fdisk -l",
  "mkfs.ext4 /dev/sda1",
  "fsck /dev/sda1",
  "umount /mnt",
  "mount /dev/sda1 /mnt",
  "modprobe -r module",
  "lsmod",
  "ln -s target linkname",
  "xargs rm < files.txt",
  "jobs",
  "bg",
  "fg",
  "pkill vim",
  "nohup command &",
  "shutdown -h now",
  "reboot",
  "halt",
  "sync",
  "gzip file.txt",
  "gunzip file.txt.gz",
  "zip archive.zip file.txt",
  "unzip archive.zip",
  "scp file.txt user@remote:/path",
  "wget http://example.com/file.txt",
  "curl http://example.com",
  "ping google.com",
  "traceroute google.com",
  "nslookup google.com",
  "ftp ftp.example.com",
  "sftp user@example.com",
  "telnet example.com",
  "ssh user@example.com",
  "exit",
  "dig example.com",
  "killall vim",
  "watch -n 1 date",
  "hostnamectl",
  "journalctl -xe",
  "systemctl status",
  "timedatectl",
  "hwclock",
  "sudo apt update",
  "sudo apt install package",
];

export default commands;
